Repository Coding-Delight-01/DSA-in-JAVA, pull requests merged in 2022-10, with the labels that each got.

#4 Added this subArray program
  arrays/SmallestSumContiguousSubarray.java
Labels: hacktoberfest-accepted

#5 Create HACTOBERFEST.md
  HACTOBERFEST.md
Labels: documentation, hacktoberfest-accepted

#8 deleted extra comment
  arrays/ArrayListExample.java
Labels: documentation, good first issue

#10 Added SortArray File In Java
  arrays/SortArray.java
Labels: hacktoberfest-accepted

#14 Create reverseArray.java
  arrays/reverseArray.java
Labels: hacktoberfest-accepted

#12 Created Duplicate Element code
  arrays/DuplicateElement.java
Labels: hacktoberfest-accepted

#16 TwoDArray.java
  TwoDArray.JAVA
Labels: hacktoberfest-accepted

#19 nested-switch
  arrays/NestedSwitch.java
Labels: good first issue, hacktoberfest-accepted

#20 minor changes
  array_short_note.java
  arrays/ArrayListExample.java
Labels: hacktoberfest-accepted

#21 Create defn_linkedlist.java
  LinkedList/defn_linkedlist.java
Labels: hacktoberfest-accepted

#15 Java Prog added
  mergeLL.java
Labels: hacktoberfest-accepted

#22 added wave array problem
  arrays/Wave_Array.java
Labels: hacktoberfest-accepted
